<<<<<<< HEAD
name: exercicio_2
description: "Row, Column, Icon e Container (barra de botoes)"
=======
name: flutter_is_fun
description: "Exercício - reprodução da interface Flutter is Fun"
>>>>>>> 60f726c5906aa48dc36d2f9356773839cca2639d
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
